using AltV.Net.Client;

namespace Los_Angeles_Life_Client.World;

public abstract class MissedInterriors : Client
{
    public static void Load() {
        Alt.RequestIpl("EX_DT1_02_OFFICE_02B");
        Alt.RequestIpl("CHOP_PROPS");
        Alt.RequestIpl("FIBLOBBY");
        Alt.RemoveIpl("FIBLOBBYFAKE");
        Alt.RequestIpl("FBI_COLPLUG");
        Alt.RequestIpl("FBI_REPAIR");
        Alt.RequestIpl("V_TUNNEL_HOLE");
        Alt.RequestIpl("TREVORSMP");
        Alt.RequestIpl("TREVORSTRAILER");
        Alt.RequestIpl("TREVORSTRAILERTIDY");
        Alt.RemoveIpl("FARM_BURNT");
        Alt.RemoveIpl("FARM_BURNT_LOD");
        Alt.RemoveIpl("FARM_BURNT_PROPS");
        Alt.RemoveIpl("FARMINT_CAP");
        Alt.RemoveIpl("FARMINT_CAP_LOD");
        Alt.RequestIpl("FARM");
        Alt.RequestIpl("FARMINT");
        Alt.RequestIpl("FARM_LOD");
        Alt.RequestIpl("FARM_PROPS");
        Alt.RequestIpl("FACELOBBY");
        Alt.RemoveIpl("CS1_02_CF_OFFMISSION");
        Alt.RequestIpl("CS1_02_CF_ONMISSION1");
        Alt.RequestIpl("CS1_02_CF_ONMISSION2");
        Alt.RequestIpl("CS1_02_CF_ONMISSION3");
        Alt.RequestIpl("CS1_02_CF_ONMISSION4");
        Alt.RequestIpl("V_ROCKCLUB");
        Alt.RequestIpl("V_JANITOR");
        Alt.RemoveIpl("HEI_BI_HW1_13_DOOR");
        Alt.RequestIpl("BKR_BI_HW1_13_INT");
        Alt.RequestIpl("UFO");
        Alt.RequestIpl("UFO_LOD");
        Alt.RequestIpl("UFO_EYE");
        Alt.RemoveIpl("V_CARSHOWROOM");
        Alt.RemoveIpl("SHUTTER_OPEN");
        Alt.RemoveIpl("SHUTTER_CLOSED");
        Alt.RemoveIpl("SHR_INT");
        Alt.RequestIpl("CSR_AFTERMISSION");
        Alt.RequestIpl("V_CARSHOWROOM");
        Alt.RequestIpl("SHR_INT");
        Alt.RequestIpl("SHUTTER_CLOSED");
        Alt.RequestIpl("SMBOAT");
        Alt.RequestIpl("SMBOAT_DISTANTLIGHTS");
        Alt.RequestIpl("SMBOAT_LOD");
        Alt.RequestIpl("SMBOAT_LODLIGHTS");
        Alt.RequestIpl("CARGOSHIP");
        Alt.RequestIpl("RAILING_START");
        Alt.RemoveIpl("SP1_10_FAKE_INTERIOR");
        Alt.RemoveIpl("SP1_10_FAKE_INTERIOR_LOD");
        Alt.RequestIpl("SP1_10_REAL_INTERIOR");
        Alt.RequestIpl("SP1_10_REAL_INTERIOR_LOD");
        Alt.RemoveIpl("ID2_14_DURING_DOOR");
        Alt.RemoveIpl("ID2_14_DURING1");
        Alt.RemoveIpl("ID2_14_DURING2");
        Alt.RemoveIpl("ID2_14_ON_FIRE");
        Alt.RemoveIpl("ID2_14_POST_NO_INT");
        Alt.RemoveIpl("ID2_14_PRE_NO_INT");
        Alt.RemoveIpl("ID2_14_DURING_DOOR");
        Alt.RequestIpl("ID2_14_DURING1");
        Alt.RemoveIpl("CORONER_INT_OFF");
        Alt.RequestIpl("CORONERTRASH");
        Alt.RequestIpl("CORONER_INT_ON");
        Alt.RemoveIpl("BH1_16_REFURB");
        Alt.RemoveIpl("JEWEL2FAKE");
        Alt.RemoveIpl("BH1_16_DOORS_SHUT");
        Alt.RequestIpl("REFIT_UNLOAD");
        Alt.RequestIpl("POST_HIEST_UNLOAD");
        Alt.RequestIpl("CARWASH_WITH_SPINNERS");
        Alt.RequestIpl("KT_CARWASH");
        Alt.RequestIpl("FERRIS_FINALE_ANIM");
        Alt.RemoveIpl("CH1_02_CLOSED");
        Alt.RequestIpl("CH1_02_OPEN");
        Alt.RequestIpl("AP1_04_TRIAF01");
        Alt.RequestIpl("CS2_06_TRIAF02");
        Alt.RequestIpl("CS4_04_TRIAF03");
        Alt.RemoveIpl("SCAFSTARTIMAP");
        Alt.RequestIpl("SCAFENDIMAP");
        Alt.RemoveIpl("DT1_05_HC_REMOVE");
        Alt.RequestIpl("DT1_05_HC_REQ");
        Alt.RequestIpl("DT1_05_REQUEST");
        Alt.RequestIpl("DT1_05_HC_REMOVE");
        Alt.RequestIpl("DT1_05_HC_REMOVE_LOD");
        Alt.RequestIpl("FINBANK");
        Alt.RemoveIpl("DT1_03_SHUTTER");
        Alt.RemoveIpl("DT1_03_GR_CLOSED");
        Alt.RequestIpl("GOLFFLAGS");
        Alt.RequestIpl("AIRFIELD");
        Alt.RequestIpl("V_GARAGES");
        Alt.RequestIpl("V_FOUNDRY");
        Alt.RequestIpl("HEI_YACHT_HEIST");
        Alt.RequestIpl("HEI_YACHT_HEIST_BAR");
        Alt.RequestIpl("HEI_YACHT_HEIST_BEDRM");
        Alt.RequestIpl("HEI_YACHT_HEIST_BRIDGE");
        Alt.RequestIpl("HEI_YACHT_HEIST_DISTANTLIGHTS");
        Alt.RequestIpl("HEI_YACHT_HEIST_ENGINRM");
        Alt.RequestIpl("HEI_YACHT_HEIST_LODLIGHTS");
        Alt.RequestIpl("HEI_YACHT_HEIST_LOUNGE");
        Alt.RequestIpl("HEI_CARRIER");
        Alt.RequestIpl("HEI_CARRIER_INT1");
        Alt.RequestIpl("HEI_CARRIER_INT2");
        Alt.RequestIpl("HEI_CARRIER_INT3");
        Alt.RequestIpl("HEI_CARRIER_INT4");
        Alt.RequestIpl("HEI_CARRIER_INT5");
        Alt.RequestIpl("HEI_CARRIER_INT6");
        Alt.RequestIpl("HEI_CARRIER_LODLIGHTS");
        Alt.RequestIpl("BKR_BI_ID1_23_DOOR");
        Alt.RequestIpl("LR_CS6_08_GRAVE_CLOSED");
        Alt.RequestIpl("HEI_SM_16_INTERIOR_V_BAHAMA_MILO_");
        Alt.RequestIpl("CS3_07_MPGATES");
        Alt.RequestIpl("CS5_4_TRAINS");
        Alt.RequestIpl("V_LESTERS");
        Alt.RequestIpl("V_TREVORS");
        Alt.RequestIpl("V_MICHAEL");
        Alt.RequestIpl("V_COMEDY");
        Alt.RequestIpl("V_CINEMA");
        Alt.RequestIpl("V_SWEAT");
        Alt.RequestIpl("V_35_FIREMAN");
        Alt.RequestIpl("REDCARPET");
        Alt.RequestIpl("TRIATHLON2_VBPROPS");
        Alt.RequestIpl("JETSTENATIVEURNEL");
        Alt.RequestIpl("JETSTEAL_IPL_GRP1");
        Alt.RequestIpl("V_HOSPITAL");
        Alt.RemoveIpl("RC12B_FIXED");
        Alt.RemoveIpl("RC12B_DESTROYED");
        Alt.RemoveIpl("RC12B_HOSPITALINTERIOR");
        Alt.RequestIpl("RC12B_DEFAULT");
        Alt.RequestIpl("CANYONRIVER01");
        Alt.RequestIpl("CANYONRIVER01_LOD");
        Alt.RequestIpl("CS3_05_WATER_GRP1");
        Alt.RequestIpl("CS3_05_WATER_GRP1_LOD");
        Alt.RequestIpl("TRV1_TRAIL_START");
        Alt.RequestIpl("CANYONRVRSALLOW");
        
        // CASINO
        Alt.RequestIpl("VW_CASINO_PENTHOUSE");
        Alt.RequestIpl("VW_CASINO_MAIN");
        Alt.RequestIpl("VW_CASINO_CARPARK");
        Alt.RequestIpl("VW_DLC_CASINO_DOOR");
        Alt.RequestIpl("VW_CASINO_DOOR");
        Alt.RequestIpl("HEI_DLC_WINDOWS_CASINO");
        Alt.RequestIpl("HEI_DLC_CASINO_DOOR");
        Alt.RequestIpl("HEI_DLC_CASINO_AIRCON");
        Alt.RequestIpl("VW_CASINO_GARAGE");

        var interiorId = Alt.Natives.GetInteriorAtCoords((float)1100.0, (float)220.0, (float)-50.0);
        if (!Alt.Natives.IsValidInterior(interiorId)) return;
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "0x30240D11");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "0xA3C89BB2");
        Alt.Natives.RefreshInterior(interiorId);

        interiorId = Alt.Natives.GetInteriorAtCoords((float)976.6364, (float)70.29476, (float)115.1641);
        if (!Alt.Natives.IsValidInterior(interiorId)) return;
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Tint_Shell");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Pattern_09");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Spa_Bar_Open");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Media_Bar_Open");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Arcade_Modern");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Bar_Clutter");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_Pent_Clutter_03");
        Alt.Natives.ActivateInteriorEntitySet(interiorId, "Set_pent_bar_light_02");
        Alt.Natives.RefreshInterior(interiorId);
    }
}