name = '[DEV] Los Angeles Life'
host = '0.0.0.0'
port = 7788
players = 4096
password = ''
debug = true
#announce = true
#token = 'k69s+xFmUvBUgfXj3a5fhN7X2tonTMhycjXoWntERP9+uuUaSl6EtTnpP0MWLn6rzxFySCVz3AwyuJOPr+hImH0F2tC8HJBysa3gxO1w6Njiji+y+8sIu/+/cCn7+YXfLRnZDwpDGviPCd3UilcKbGqTqOLlKOOUIXCVh4wfpKKTZCrvzOZAhs3HXzrOBSZmo+GEjDbHyHGHpDpbvQQ1a8HDEVoxXznHSeUwzN/kVthx4nDZac+XbinCGrYTZTXdeC7LatOA/gZmYz14DXxhtuCP3Kmnt/FeZPw4HXwV29EnI1lPUUp6C/0RXLszka6EvvG4H44gGwimZTgUfwikLQ=='
gamemode = 'Hardcore Roleplay'
website = 'https://discord.gg/TwBa2vAndG'
language = 'de'
description = 'Deutscher Hardcore Roleplay Server - In Entwicklung'
modules = ['js-module', 'js-bytecode-module', 'csharp-module']
resources = ['chat', 'server', 'client']
[voice]